FROM alpine as build

# Install build tools
RUN apk add --no-cache build-base 

# Copy source into build stage
COPY sender.c /tmp

# Build snd binary
RUN cd /tmp                   && \
    gcc -o snd sender.c -lrt

FROM alpine

# Copy built binary from build stage
COPY --from=build /tmp/snd /usr/local/bin

ENTRYPOINT ["snd"]
